107-2 大數據分析方法 作業一
================
B0544203石家安

搞不清楚各行各業的薪資差異嗎? 念研究所到底對第一份工作的薪資影響有多大? CP值高嗎? 透過分析**初任人員平均經常性薪資**- [開放資料連結](https://data.gov.tw/dataset/6647)，可初步了解台灣近幾年各行各業、各學歷的起薪。

比較103年度和106年度大學畢業者的薪資資料
----------------------------------------

### 資料匯入與處理

-   載入packages

``` r
library(readr)
```

    ## Warning: package 'readr' was built under R version 3.5.3

``` r
library(dplyr)
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

-   將指定檔案匯入r

``` r
education103 <- read_csv("~/R/hw1/education103.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   年度 = col_double(),
    ##   大職業別 = col_character(),
    ##   `經常性薪資-薪資` = col_double(),
    ##   `經常性薪資-女/男` = col_double(),
    ##   `國中及以下-薪資` = col_character(),
    ##   `國中及以下-女/男` = col_character(),
    ##   `高中或高職-薪資` = col_character(),
    ##   `高中或高職-女/男` = col_character(),
    ##   `專科-薪資` = col_character(),
    ##   `專科-女/男` = col_character(),
    ##   `大學-薪資` = col_character(),
    ##   `大學-女/男` = col_character(),
    ##   `研究所及以上-薪資` = col_character(),
    ##   `研究所及以上-女/男` = col_character()
    ## )

``` r
education104 <- read_csv("~/R/hw1/education104.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   年度 = col_double(),
    ##   大職業別 = col_character(),
    ##   `經常性薪資-薪資` = col_double(),
    ##   `經常性薪資-女/男` = col_character(),
    ##   `國中及以下-薪資` = col_character(),
    ##   `國中及以下-女/男` = col_character(),
    ##   `高中或高職-薪資` = col_character(),
    ##   `高中或高職-女/男` = col_character(),
    ##   `專科-薪資` = col_character(),
    ##   `專科-女/男` = col_character(),
    ##   `大學-薪資` = col_character(),
    ##   `大學-女/男` = col_character(),
    ##   `研究所及以上-薪資` = col_character(),
    ##   `研究所及以上-女/男` = col_character()
    ## )

``` r
education105 <- read_csv("~/R/hw1/education105.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   年度 = col_double(),
    ##   大職業別 = col_character(),
    ##   `經常性薪資-薪資` = col_double(),
    ##   `經常性薪資-女/男` = col_character(),
    ##   `國中及以下-薪資` = col_character(),
    ##   `國中及以下-女/男` = col_character(),
    ##   `高中或高職-薪資` = col_character(),
    ##   `高中或高職-女/男` = col_character(),
    ##   `專科-薪資` = col_character(),
    ##   `專科-女/男` = col_character(),
    ##   `大學-薪資` = col_character(),
    ##   `大學-女/男` = col_character(),
    ##   `研究所及以上-薪資` = col_character(),
    ##   `研究所及以上-女/男` = col_character()
    ## )

``` r
education106 <- read_csv("~/R/hw1/education106.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   年度 = col_double(),
    ##   大職業別 = col_character(),
    ##   `經常性薪資-薪資` = col_double(),
    ##   `經常性薪資-女/男` = col_character(),
    ##   `國中及以下-薪資` = col_character(),
    ##   `國中及以下-女/男` = col_character(),
    ##   `高中或高職-薪資` = col_character(),
    ##   `高中或高職-女/男` = col_character(),
    ##   `專科-薪資` = col_character(),
    ##   `專科-女/男` = col_character(),
    ##   `大學-薪資` = col_character(),
    ##   `大學-女/男` = col_character(),
    ##   `研究所及以上-薪資` = col_character(),
    ##   `研究所及以上-女/男` = col_character()
    ## )

-   取出需用到的欄位(年度、職業類別、"大學"畢業薪資)，為了讀取方便將選取欄位重新命名<br/> 設定stringsAsFactors = F，以防止欄位以Factor之型態儲存

``` r
education103N1<-data.frame(Job=education103$大職業別,
                         Salary_College=education103$`大學-薪資`,stringsAsFactors = F) 
education106N1<-data.frame(Job=education106$大職業別,
                         Salary_College=education106$`大學-薪資`,stringsAsFactors = F)
```

-   透過職業別inner\_join，篩選出103與106都有的職業別，故by用Job欄位進行篩選<br/> 此外，為了讀取方便將選取欄位重新命名

``` r
edu103to106<-inner_join(education103N1,education106N1,by="Job")
names(edu103to106)<-c("Job","Salary103_College","Salary106_College")
```

-   將原Dataframe薪資表空值的符號—，轉為NA<br/>
-   新增一欄位比較103與106的畢業薪資，故需將原character型態的兩薪資欄位轉為numeric

``` r
edu103to106$Salary103_College<-gsub("—","NA",edu103to106$Salary103_College)
edu103to106$Salary106_College<-gsub("—","NA",edu103to106$Salary106_College)

edu103to106$Salary103_College<-as.numeric(edu103to106$Salary103_College)
edu103to106$Salary106_College<-as.numeric(edu103to106$Salary106_College)

edu103to106$SalaryIncrease<-edu103to106$Salary106_College/edu103to106$Salary103_College
```

### 106年度薪資較103年度薪資高的職業有哪些?

-   篩選106年薪資較103年度高的職業，故以row做子集，並將提高的職業另外存成HigherWage變數<br/>
-   列出薪資以大到小提高的順序，並呈現前十名的資料，因此用head函數

``` r
HigherWage<-filter(edu103to106,SalaryIncrease>1) 
HigherWage<-HigherWage[order(HigherWage$SalaryIncrease,decreasing = T),]
knitr::kable(head(HigherWage,10)) 
```

|     | Job                                       |  Salary103\_College|  Salary106\_College|  SalaryIncrease|
|-----|:------------------------------------------|-------------------:|-------------------:|---------------:|
| 76  | 其他服務業-技術員及助理專業人員           |               24688|               27929|        1.131278|
| 47  | 住宿及餐飲業-服務及銷售工作人員           |               22564|               25486|        1.129498|
| 20  | 用水供應及污染整治業-技術員及助理專業人員 |               27944|               31560|        1.129402|
| 27  | 營造業-服務及銷售工作人員                 |               27164|               30125|        1.109005|
| 75  | 其他服務業-專業人員                       |               29000|               32000|        1.103448|
| 49  | 資訊及通訊傳播業-專業人員                 |               28839|               31817|        1.103263|
| 58  | 不動產業-專業人員                         |               30637|               33632|        1.097758|
| 67  | 教育服務業-事務支援人員                   |               22334|               24471|        1.095684|
| 45  | 住宿及餐飲業-技術員及助理專業人員         |               25633|               28009|        1.092693|
| 77  | 其他服務業-事務支援人員                   |               23863|               26007|        1.089846|

1.  結果得知「其他服務業-技術員及助理專業人員」薪水漲幅最高(共漲幅1.13%)，此外，前10名中「住宿及餐飲業」職業種類薪資漲幅度就佔了兩名(第2、9名)<br/>
2.  儘管「其他服務業」與「住宿及餐飲業」職業種類薪資有明顯的漲幅度，但於前10名中，從薪水欄 位卻另外得知他們起薪相對較低，如「用水供應及污染整治業」的研究所畢業起薪為31560，但「其他服務業」與「住宿及餐飲業」起薪大概28000，因此推測由於他們起薪相對較低，故薪水漲幅度才會較明顯。

### 提高超過5%的的職業有哪些?

``` r
OverFivePercent<-HigherWage[HigherWage$SalaryIncrease>1.05,]
OverFivePercent<-OverFivePercent[complete.cases(OverFivePercent),]
knitr::kable(OverFivePercent) 
```

|     | Job                                       |  Salary103\_College|  Salary106\_College|  SalaryIncrease|
|-----|:------------------------------------------|-------------------:|-------------------:|---------------:|
| 76  | 其他服務業-技術員及助理專業人員           |               24688|               27929|        1.131278|
| 47  | 住宿及餐飲業-服務及銷售工作人員           |               22564|               25486|        1.129498|
| 20  | 用水供應及污染整治業-技術員及助理專業人員 |               27944|               31560|        1.129402|
| 27  | 營造業-服務及銷售工作人員                 |               27164|               30125|        1.109005|
| 75  | 其他服務業-專業人員                       |               29000|               32000|        1.103448|
| 49  | 資訊及通訊傳播業-專業人員                 |               28839|               31817|        1.103263|
| 58  | 不動產業-專業人員                         |               30637|               33632|        1.097758|
| 67  | 教育服務業-事務支援人員                   |               22334|               24471|        1.095684|
| 45  | 住宿及餐飲業-技術員及助理專業人員         |               25633|               28009|        1.092693|
| 77  | 其他服務業-事務支援人員                   |               23863|               26007|        1.089846|
| 68  | 教育服務業-服務及銷售工作人員             |               24491|               26668|        1.088890|
| 18  | 用水供應及污染整治業                      |               27456|               29834|        1.086611|
| 19  | 用水供應及污染整治業-專業人員             |               31444|               34107|        1.084690|
| 48  | 資訊及通訊傳播業                          |               27055|               29198|        1.079209|
| 63  | 支援服務業-服務及銷售工作人員             |               24166|               26001|        1.075933|
| 51  | 資訊及通訊傳播業-事務支援人員             |               25276|               27156|        1.074379|
| 64  | 教育服務業                                |               24027|               25784|        1.073126|
| 24  | 營造業-專業人員                           |               30580|               32785|        1.072106|
| 43  | 住宿及餐飲業                              |               24646|               26398|        1.071087|
| 17  | 電力及燃氣供應業-服務及銷售工作人員       |               26013|               27837|        1.070119|
| 40  | 運輸及倉儲業-技術員及助理專業人員         |               28974|               30993|        1.069683|
| 41  | 運輸及倉儲業-事務支援人員                 |               25886|               27685|        1.069497|
| 71  | 醫療保健服務業-技術員及助理專業人員       |               28465|               30392|        1.067697|
| 61  | 支援服務業-技術員及助理專業人員           |               26933|               28696|        1.065459|
| 22  | 用水供應及污染整治業-服務及銷售工作人員   |               28736|               30593|        1.064623|
| 66  | 教育服務業-技術員及助理專業人員           |               25675|               27250|        1.061344|
| 29  | 服務業部門-專業人員                       |               30806|               32632|        1.059274|
| 38  | 運輸及倉儲業                              |               28143|               29808|        1.059162|
| 50  | 資訊及通訊傳播業-技術員及助理專業人員     |               27288|               28902|        1.059147|
| 21  | 用水供應及污染整治業-事務支援人員         |               25430|               26924|        1.058750|
| 56  | 金融及保險業-事務支援人員                 |               29070|               30771|        1.058514|
| 30  | 服務業部門-技術員及助理專業人員           |               27882|               29504|        1.058174|
| 26  | 營造業-事務支援人員                       |               24892|               26256|        1.054797|
| 2   | 工業及服務業部門-專業人員                 |               30449|               32108|        1.054485|
| 31  | 服務業部門-事務支援人員                   |               25554|               26930|        1.053847|
| 65  | 教育服務業-專業人員                       |               25722|               27101|        1.053612|
| 28  | 服務業部門                                |               27258|               28715|        1.053452|
| 74  | 其他服務業                                |               24232|               25517|        1.053029|
| 13  | 製造業-專業人員                           |               30035|               31612|        1.052505|
| 7   | 工業部門-專業人員                         |               30215|               31775|        1.051630|
| 52  | 資訊及通訊傳播業-服務及銷售工作人員       |               25995|               27296|        1.050048|

1.  從表得知薪資有明顯漲幅的職業共有41個，故一共有36個職業並未有明顯之漲幅(另外以nrow(HigherWage)-nrow(OverFivePercent)=36得知)

### 主要的職業種別是哪些種類呢?

-   使用strsplit取出職業別中"-" 前面的字串，了解是那些職業種類，
-   將後方的子職業篩選掉，留下主要職業種類別，由於切割完之字串為list型態，故轉乘向量之型態
-   用table計算次數，並以次數最多至最小排序列出主要職業別

``` r
JobType<-strsplit(OverFivePercent$Job,"-")
for(n in 1:length(JobType)){
  JobType[n]<-JobType[[n]][1]
}
knitr::kable( sort(table(unlist(JobType)),decreasing = T) ) 
```

| Var1                 |  Freq|
|:---------------------|-----:|
| 用水供應及污染整治業 |     5|
| 教育服務業           |     5|
| 資訊及通訊傳播業     |     5|
| 其他服務業           |     4|
| 服務業部門           |     4|
| 住宿及餐飲業         |     3|
| 運輸及倉儲業         |     3|
| 營造業               |     3|
| 支援服務業           |     2|
| 工業及服務業部門     |     1|
| 工業部門             |     1|
| 不動產業             |     1|
| 金融及保險業         |     1|
| 電力及燃氣供應業     |     1|
| 製造業               |     1|
| 醫療保健服務業       |     1|

1.  用水供應及污染整治業、教育服務業、資訊及通訊傳播業為主要的薪資漲幅度主要職業別 <br/>推測: 因這些產業都需要相對規模專業的知識，故可能為漲幅度之原因

男女同工不同酬現況分析
----------------------

男女同工不同酬一直是性別平等中很重要的問題，分析資料來源為103到106年度的大學畢業薪資。

### 103到106年度的大學畢業薪資資料，哪些行業男生薪資比女生薪資多?

#### 資料處理

-   篩選各年之資料，將不完整之資料篩掉(—|…)
-   新增一欄位(status)表男女薪資比是否有差異
-   M\_wage\_More\_F\_wage 男生薪資多於女生薪資
-   F\_wage\_More\_M\_wage 女生薪資多於男生薪資
-   F\_wage\_Equal\_M\_wage 男生薪資等於女生薪資

``` r
#103
edu103N3<-data.frame(Job=education103$大職業別,UniWage103=education103$`大學-薪資`,
                     FMUniwage103=education103$`大學-女/男`,stringsAsFactors = F)
edu103N3<-edu103N3[!grepl("—|…",edu103N3$FMUniwage103),]
edu103N3$FMUniwage103<-as.numeric(edu103N3$FMUniwage103)
edu103N3$status<-ifelse(edu103N3$FMUniwage103<100,"M_wage_More_F_wage",
                        ifelse(edu103N3$FMUniwage103>100,"F_wage_More_M_wage"
                               ,"F_wage_Equal_M_wage"))
#104
edu104N3<-data.frame(Job=education104$大職業別,UniWage104=education104$`大學-薪資`,
                     FMUniwage104=education104$`大學-女/男`,stringsAsFactors = F)
edu104N3<-edu104N3[!grepl("—|…",edu104N3$FMUniwage104),]
edu104N3$FMUniwage104<-as.numeric(edu104N3$FMUniwage104)
edu104N3$status<-ifelse(edu104N3$FMUniwage104<100,"M_wage_More_F_wage",
                        ifelse(edu104N3$FMUniwage104>100,"F_wage_More_M_wage"
                               ,"F_wage_Equal_M_wage"))
#105
edu105N3<-data.frame(Job=education105$大職業別,UniWage105=education105$`大學-薪資`,
                     FMUniwage105=education105$`大學-女/男`,stringsAsFactors = F)
edu105N3<-edu105N3[!grepl("—|…",edu105N3$FMUniwage105),]
edu105N3$FMUniwage105<-as.numeric(edu105N3$FMUniwage105)
edu105N3$status<-ifelse(edu105N3$FMUniwage105<100,"M_wage_More_F_wage",
                        ifelse(edu105N3$FMUniwage105>100,"F_wage_More_M_wage"
                               ,"F_wage_Equal_M_wage"))
#106
edu106N3<-data.frame(Job=education106$大職業別,UniWage106=education106$`大學-薪資`,
                     FMUniwage106=education106$`大學-女/男`,stringsAsFactors = F)
edu106N3<-edu106N3[!grepl("—|…",edu106N3$FMUniwage106),]
edu106N3$FMUniwage106<-as.numeric(edu106N3$FMUniwage106)
edu106N3$status<-ifelse(edu106N3$FMUniwage106<100,"M_wage_More_F_wage",
                        ifelse(edu106N3$FMUniwage106>100,"F_wage_More_M_wage"
                               ,"F_wage_Equal_M_wage"))
```

##### 哪些行業男生薪資比女生薪資多?

-   103年

``` r
#103
MMoreF103<-edu103N3[order(edu103N3$FMUniwage103),]
knitr::kable(head(MMoreF103,10)) 
```

|     | Job                                                 | UniWage103 |  FMUniwage103| status                 |
|-----|:----------------------------------------------------|:-----------|-------------:|:-----------------------|
| 20  | 礦業及土石採取業-技藝、機械設備操作及組裝人員       | 26647      |         84.97| M\_wage\_More\_F\_wage |
| 118 | 教育服務業-技藝、機械設備操作及組裝人員             | 24244      |         88.49| M\_wage\_More\_F\_wage |
| 136 | 其他服務業-技術員及助理專業人員                     | 24688      |         89.36| M\_wage\_More\_F\_wage |
| 34  | 電力及燃氣供應業-技藝、機械設備操作及組裝人員       | 27253      |         91.77| M\_wage\_More\_F\_wage |
| 19  | 礦業及土石採取業-服務及銷售工作人員                 | 24659      |         92.57| M\_wage\_More\_F\_wage |
| 43  | 營造業                                              | 27596      |         95.58| M\_wage\_More\_F\_wage |
| 116 | 教育服務業-事務支援人員                             | 22334      |         95.83| M\_wage\_More\_F\_wage |
| 113 | 教育服務業                                          | 24027      |         95.91| M\_wage\_More\_F\_wage |
| 132 | 藝術、娛樂及休閒服務業-技藝、機械設備操作及組裝人員 | 24895      |         96.13| M\_wage\_More\_F\_wage |
| 134 | 其他服務業                                          | 24232      |         96.21| M\_wage\_More\_F\_wage |

1.  由MMoreF103得知於103產業中，於前10名中，多數有薪資差異之職位為，大職業別的子職業別為:技藝、機械設備操作及組裝人員
2.  推測:技藝、機械設備操作及組裝人員之工作內容需強大的勞力與力氣，故部分男生做事效率可能會比大部分女生做事效率，故薪資會比女生高

-   104年

``` r
#104
MMoreF104<-edu104N3[order(edu104N3$FMUniwage104),]
knitr::kable(head(MMoreF104,10))
```

|     | Job                                               | UniWage104 |  FMUniwage104| status                 |
|-----|:--------------------------------------------------|:-----------|-------------:|:-----------------------|
| 34  | 電力及燃氣供應業-技藝、機械設備操作及組裝人員     | 28039      |         91.69| M\_wage\_More\_F\_wage |
| 117 | 教育服務業-服務及銷售工作人員                     | 24324      |         91.90| M\_wage\_More\_F\_wage |
| 17  | 礦業及土石採取業-技術員及助理專業人員             | 29313      |         92.42| M\_wage\_More\_F\_wage |
| 20  | 礦業及土石採取業-技藝、機械設備操作及組裝人員     | 28688      |         93.10| M\_wage\_More\_F\_wage |
| 15  | 礦業及土石採取業                                  | 30232      |         95.28| M\_wage\_More\_F\_wage |
| 137 | 其他服務業-事務支援人員                           | 25846      |         95.47| M\_wage\_More\_F\_wage |
| 48  | 營造業-技藝、機械設備操作及組裝人員               | 26650      |         95.64| M\_wage\_More\_F\_wage |
| 41  | 用水供應及污染整治業-技藝、機械設備操作及組裝人員 | 27887      |         95.90| M\_wage\_More\_F\_wage |
| 43  | 營造業                                            | 27748      |         96.35| M\_wage\_More\_F\_wage |
| 113 | 教育服務業                                        | 25162      |         96.44| M\_wage\_More\_F\_wage |

1.  由MMoreF103得知於103產業中，於前10名中，多數有薪資差異之職位為，大職業別的子職業別仍為:技藝、機械設備操作及組裝人員
2.  推測原因如上述所說

-   105年

``` r
#105
MMoreF105<-edu105N3[order(edu105N3$FMUniwage105),]
knitr::kable(head(MMoreF105,10))
```

|     | Job                                           | UniWage105 |  FMUniwage105| status                 |
|-----|:----------------------------------------------|:-----------|-------------:|:-----------------------|
| 97  | 不動產業-技藝、機械設備操作及組裝人員         | 25029      |         91.38| M\_wage\_More\_F\_wage |
| 121 | 醫療保健服務業-專業人員                       | 34708      |         94.98| M\_wage\_More\_F\_wage |
| 39  | 用水供應及污染整治業-事務支援人員             | 26984      |         95.04| M\_wage\_More\_F\_wage |
| 46  | 營造業-事務支援人員                           | 26080      |         95.65| M\_wage\_More\_F\_wage |
| 95  | 不動產業-事務支援人員                         | 25912      |         95.66| M\_wage\_More\_F\_wage |
| 43  | 營造業                                        | 28815      |         95.78| M\_wage\_More\_F\_wage |
| 44  | 營造業-專業人員                               | 32830      |         96.52| M\_wage\_More\_F\_wage |
| 83  | 資訊及通訊傳播業-技藝、機械設備操作及組裝人員 | 27702      |         96.64| M\_wage\_More\_F\_wage |
| 96  | 不動產業-服務及銷售工作人員                   | 24356      |         96.68| M\_wage\_More\_F\_wage |
| 134 | 其他服務業                                    | 25440      |         96.72| M\_wage\_More\_F\_wage |

1.  由MMoreF105得知於105產業中，今年男生薪資比女生薪資高的前10名，與前兩年之呈現較不一樣，「技藝、機械設備操作及組裝人員」職業之薪資差異度大幅減少。

-   106年

``` r
#106
MMoreF106<-edu106N3[order(edu106N3$FMUniwage106),]
knitr::kable(head(MMoreF106,10))
```

|     | Job                                           | UniWage106 |  FMUniwage106| status                 |
|-----|:----------------------------------------------|:-----------|-------------:|:-----------------------|
| 34  | 電力及燃氣供應業-技藝\_機械設備操作及組裝人員 | 28717      |         95.51| M\_wage\_More\_F\_wage |
| 47  | 營造業-服務及銷售工作人員                     | 30125      |         95.93| M\_wage\_More\_F\_wage |
| 137 | 其他服務業-事務支援人員                       | 26007      |         96.23| M\_wage\_More\_F\_wage |
| 31  | 電力及燃氣供應業-技術員及助理專業人員         | 29970      |         96.54| M\_wage\_More\_F\_wage |
| 134 | 其他服務業                                    | 25517      |         96.57| M\_wage\_More\_F\_wage |
| 76  | 住宿及餐飲業-技藝\_機械設備操作及組裝人員     | 26585      |         96.58| M\_wage\_More\_F\_wage |
| 43  | 營造業                                        | 28952      |         96.71| M\_wage\_More\_F\_wage |
| 114 | 教育服務業-專業人員                           | 27101      |         96.71| M\_wage\_More\_F\_wage |
| 67  | 運輸及倉儲業-事務支援人員                     | 27685      |         96.83| M\_wage\_More\_F\_wage |
| 136 | 其他服務業-技術員及助理專業人員               | 27929      |         96.84| M\_wage\_More\_F\_wage |

1.  對比四張表，從103年表之男女新資之最高差異比為(84.97)，到106年表之男女新資之最高差異比為(95.51)，男女薪資比有明顯的縮小，表示，**現今產業越來越重視性別平等**

### 哪些行業女生薪資比男生薪資多?

-   103年

``` r
#103
FMoreM103<-edu103N3[order(edu103N3$FMUniwage103,decreasing = T),]
knitr::kable(head(FMoreM103,10)) 
```

|     | Job                                       | UniWage103 |  FMUniwage103| status                  |
|-----|:------------------------------------------|:-----------|-------------:|:------------------------|
| 17  | 礦業及土石採取業-技術員及助理專業人員     | 30375      |        100.00| F\_wage\_Equal\_M\_wage |
| 40  | 用水供應及污染整治業-服務及銷售工作人員   | 28736      |        100.00| F\_wage\_Equal\_M\_wage |
| 47  | 營造業-服務及銷售工作人員                 | 27164      |        100.00| F\_wage\_Equal\_M\_wage |
| 73  | 住宿及餐飲業-技術員及助理專業人員         | 25633      |         99.97| M\_wage\_More\_F\_wage  |
| 86  | 金融及保險業-專業人員                     | 33642      |         99.91| M\_wage\_More\_F\_wage  |
| 59  | 批發及零售業-技術員及助理專業人員         | 27317      |         99.87| M\_wage\_More\_F\_wage  |
| 72  | 住宿及餐飲業-專業人員                     | 28768      |         99.86| M\_wage\_More\_F\_wage  |
| 124 | 醫療保健服務業-服務及銷售工作人員         | 25260      |         99.86| M\_wage\_More\_F\_wage  |
| 131 | 藝術、娛樂及休閒服務業-服務及銷售工作人員 | 23419      |         99.74| M\_wage\_More\_F\_wage  |
| 111 | 支援服務業-技藝、機械設備操作及組裝人員   | 25365      |         99.73| M\_wage\_More\_F\_wage  |

1.  由FMoreM103得知於103產業中幾乎全部的產業男生薪資高於女生，除了:礦業及土石採取業-技術員及助理專業人員、用水供應及污染整治業-服務及銷售工作人員、營造業-服務及銷售工作人，男女薪資平等沒有差異

-   104年

``` r
#104
FMoreM104<-edu104N3[order(edu104N3$FMUniwage104,decreasing = T),]
knitr::kable(head(FMoreM104,10))
```

|     | Job                                                 | UniWage104 |  FMUniwage104| status                  |
|-----|:----------------------------------------------------|:-----------|-------------:|:------------------------|
| 104 | 專業、科學及技術服務業-技藝、機械設備操作及組裝人員 | 27294      |        100.26| F\_wage\_More\_M\_wage  |
| 40  | 用水供應及污染整治業-服務及銷售工作人員             | 30048      |        100.00| F\_wage\_Equal\_M\_wage |
| 97  | 不動產業-技藝、機械設備操作及組裝人員               | 25204      |        100.00| F\_wage\_Equal\_M\_wage |
| 124 | 醫療保健服務業-服務及銷售工作人員                   | 25106      |        100.00| F\_wage\_Equal\_M\_wage |
| 135 | 其他服務業-專業人員                                 | 30978      |        100.00| F\_wage\_Equal\_M\_wage |
| 73  | 住宿及餐飲業-技術員及助理專業人員                   | 26945      |         99.93| M\_wage\_More\_F\_wage  |
| 108 | 支援服務業-技術員及助理專業人員                     | 27413      |         99.92| M\_wage\_More\_F\_wage  |
| 75  | 住宿及餐飲業-服務及銷售工作人員                     | 23548      |         99.90| M\_wage\_More\_F\_wage  |
| 38  | 用水供應及污染整治業-技術員及助理專業人員           | 30378      |         99.78| M\_wage\_More\_F\_wage  |
| 69  | 運輸及倉儲業-技藝、機械設備操作及組裝人員           | 29168      |         99.76| M\_wage\_More\_F\_wage  |

1.  由FMoreM104得知於104產業中，「專業、科學及技術服務業-技藝、機械設備操作及組裝人員」女生薪資略高於男生，而，用水供應及污染整治業-服務及銷售工作人員、不動產業-技藝、機械設備操作及組裝人員、醫療保健服務業-服務及銷售工作人員、其他服務業-專業人員，男女薪資平等沒有差異，其餘的職業男生薪資仍高於女生
2.  推測，「專業、科學及技術服務業-技藝、機械設備操作及組裝人員」職業之刻板印象偏好男生從事，可能此產業少部分女性於此年工作較比男性認真，故薪水略高於男生

-   105年

``` r
#105
FMoreM105<-edu105N3[order(edu105N3$FMUniwage105,decreasing = T),]
knitr::kable(head(FMoreM105,10))
```

|     | Job                                         | UniWage105 |  FMUniwage105| status                  |
|-----|:--------------------------------------------|:-----------|-------------:|:------------------------|
| 86  | 金融及保險業-專業人員                       | 33468      |        100.11| F\_wage\_More\_M\_wage  |
| 19  | 礦業及土石採取業-服務及銷售工作人員         | 27594      |        100.00| F\_wage\_Equal\_M\_wage |
| 40  | 用水供應及污染整治業-服務及銷售工作人員     | 30230      |        100.00| F\_wage\_Equal\_M\_wage |
| 117 | 教育服務業-服務及銷售工作人員               | 25502      |        100.00| F\_wage\_Equal\_M\_wage |
| 125 | 醫療保健服務業-技藝、機械設備操作及組裝人員 | 28711      |        100.00| F\_wage\_Equal\_M\_wage |
| 129 | 藝術、娛樂及休閒服務業-技術員及助理專業人員 | 26841      |        100.00| F\_wage\_Equal\_M\_wage |
| 48  | 營造業-技藝、機械設備操作及組裝人員         | 26716      |         99.99| M\_wage\_More\_F\_wage  |
| 38  | 用水供應及污染整治業-技術員及助理專業人員   | 31084      |         99.98| M\_wage\_More\_F\_wage  |
| 76  | 住宿及餐飲業-技藝、機械設備操作及組裝人員   | 26350      |         99.96| M\_wage\_More\_F\_wage  |
| 62  | 批發及零售業-技藝、機械設備操作及組裝人員   | 27150      |         99.90| M\_wage\_More\_F\_wage  |

1.  由FMoreM105得知於105產業中，「金融及保險業-專業人員」女生薪資略高於男生
2.  而105年男女薪資平等之職業則比前兩年多一點，但，仍有大部分之職業男生薪資仍高於女生
3.  推測，「金融及保險業-專業人員」女生薪資略高於男生，因此產業之薪水配給可能為業績，故，只要女生於今年之業績較好，薪水自然會變高

-   106年

``` r
#106
FMoreM106<-edu106N3[order(edu106N3$FMUniwage106,decreasing = T),]
knitr::kable(head(FMoreM106,10))
```

|     | Job                                                 | UniWage106 |  FMUniwage106| status                  |
|-----|:----------------------------------------------------|:-----------|-------------:|:------------------------|
| 82  | 資訊及通訊傳播業-服務及銷售工作人員                 | 27296      |        100.33| F\_wage\_More\_M\_wage  |
| 17  | 礦業及土石採取業-技術員及助理專業人員               | 27319      |        100.00| F\_wage\_Equal\_M\_wage |
| 40  | 用水供應及污染整治業-服務及銷售工作人員             | 30593      |        100.00| F\_wage\_Equal\_M\_wage |
| 83  | 資訊及通訊傳播業-技藝\_機械設備操作及組裝人員       | 27200      |        100.00| F\_wage\_Equal\_M\_wage |
| 90  | 金融及保險業-技藝\_機械設備操作及組裝人員           | 29875      |        100.00| F\_wage\_Equal\_M\_wage |
| 93  | 不動產業-專業人員                                   | 33632      |        100.00| F\_wage\_Equal\_M\_wage |
| 96  | 不動產業-服務及銷售工作人員                         | 25913      |        100.00| F\_wage\_Equal\_M\_wage |
| 97  | 不動產業-技藝\_機械設備操作及組裝人員               | 26695      |        100.00| F\_wage\_Equal\_M\_wage |
| 104 | 專業\_科學及技術服務業-技藝\_機械設備操作及組裝人員 | 28595      |        100.00| F\_wage\_Equal\_M\_wage |
| 75  | 住宿及餐飲業-服務及銷售工作人員                     | 25486      |         99.98| M\_wage\_More\_F\_wage  |

1.  由FMoreM106得知於106產業中，「資訊及通訊傳播業-服務及銷售工作人員」女生薪資略高於男生
2.  而106年男女薪資平等之職業又比去年多，表示，**現今產業越來越重視性別平等**，
3.  此外，於此表得知大部分薪資平等所從事的多為「服務及銷售工作人員」，<br/> 推測，女生越來越喜歡從事此類職位，且也可能是此類重視服務，故可能只要服務態度好，被服務的顧客越多，薪資越高

研究所薪資差異
--------------

以106年度的資料來看，哪個職業別念研究所最划算呢 (研究所學歷薪資與大學學歷薪資增加比例最多)?

### 資料處理

-   取需用到的欄位(職業類別、大學畢業薪資、研究所以上畢業薪資)，為讓讀取方便將欄位重新命名<br/>
-   將原Dataframe薪資表空值的符號—，轉為NA <br/>
-   新增一欄位比較大學與研究所以上的畢業薪資(研究所薪資 / 大學薪資)，故需將原character型態的兩薪資欄位轉為numeric

``` r
GradAndUni<-data.frame(Job=education106$大職業別,CollegeSalary=education106$`大學-薪資`,
                       GraduateSchoolSalary=education106$`研究所及以上-薪資`,
                       stringsAsFactors = F) 

GradAndUni$CollegeSalary<-gsub("—","NA",GradAndUni$CollegeSalary)
GradAndUni$GraduateSchoolSalary<-gsub("—","NA",GradAndUni$GraduateSchoolSalary)

GradAndUni$CollegeSalary<-as.numeric(GradAndUni$CollegeSalary)
GradAndUni$GraduateSchoolSalary<-as.numeric(GradAndUni$GraduateSchoolSalary)

GradAndUni$IncreaseRate<-GradAndUni$GraduateSchoolSalary/GradAndUni$CollegeSalary
```

-   篩選出研究所以上畢業薪資較大學畢業薪資高的職業，故以row做子集，
-   列出薪資以大到小提高的順序，並呈現前十名的資料，因此用head函數

``` r
GradAndUni<-filter(GradAndUni,IncreaseRate>1) 
GradAndUni<-GradAndUni[order(GradAndUni$IncreaseRate,decreasing = T),]
knitr::kable( head(GradAndUni,10) )
```

|     | Job                                 |  CollegeSalary|  GraduateSchoolSalary|  IncreaseRate|
|-----|:------------------------------------|--------------:|---------------------:|-------------:|
| 12  | 礦業及土石採取業-事務支援人員       |          24815|                 30000|      1.208946|
| 57  | 專業\_科學及技術服務業              |          29648|                 35666|      1.202982|
| 79  | 其他服務業-技術員及助理專業人員     |          27929|                 33500|      1.199470|
| 60  | 專業\_科學及技術服務業-事務支援人員 |          27035|                 32234|      1.192306|
| 33  | 批發及零售業                        |          27611|                 32910|      1.191916|
| 13  | 製造業                              |          28155|                 33458|      1.188350|
| 76  | 藝術\_娛樂及休閒服務業-事務支援人員 |          24970|                 29657|      1.187705|
| 5   | 工業部門                            |          28263|                 33448|      1.183455|
| 1   | 工業及服務業部門                    |          28446|                 33633|      1.182346|
| 29  | 服務業部門                          |          28715|                 33922|      1.181334|

1.  從答案可知從事「礦業及土石採取業-事務支援人員」職業讀研究所是最好的，因相較於大學畢業薪資，研究所畢業後的薪資整整漲幅1.21% <br/>
2.  此外，「專業\_科學及技術服務業」研究所畢業薪資也漲幅很多(1.20%)，特別是其中的「事務支援人員」職位，薪資也漲幅1.19% <br/>
3.  然而，儘管「礦業及土石採取業-事務支援人員」薪資漲幅較大，但在前10名中，「礦業及土石採取業-事務支援人員」職業的起薪卻是最低的，故由此可猜測，薪資漲幅度有顯著差異，可能是因為起薪相對較低

我有興趣的職業別薪資狀況分析
----------------------------

### 有興趣的職業別篩選，呈現薪資

-   篩選自己有興趣的職業別:<br/> **資訊及通訊傳播業、專業\_科學及技術服務業、金融及保險業**

``` r
Intrested<-filter(GradAndUni,grepl("^資訊及通訊傳播業|^專業_科學及技術服務業|^金融及保險業",Job))
```

### 這些職業別研究所薪資與大學薪資差多少呢？

-   新增一欄位(GapWithGraAndCol)比較大學與研究所以上的畢業薪資明確之相差金額(研究所薪資 - 大學薪資)，
-   為呈現相對應的大學畢業薪資與研究所畢業薪資，故將不完整之資料篩選掉

``` r
Intrested$GapWithGraAndCol<-Intrested$GraduateSchoolSalary-Intrested$CollegeSalary

Intrested<-Intrested[complete.cases(Intrested),]
Intrested<-Intrested[order(Intrested$GraduateSchoolSalary,decreasing = T),]

knitr::kable(Intrested)
```

|     | Job                                         |  CollegeSalary|  GraduateSchoolSalary|  IncreaseRate|  GapWithGraAndCol|
|-----|:--------------------------------------------|--------------:|---------------------:|-------------:|-----------------:|
| 9   | 金融及保險業-專業人員                       |          33646|                 38542|      1.145515|              4896|
| 6   | 專業\_科學及技術服務業-專業人員             |          33384|                 38415|      1.150701|              5031|
| 5   | 金融及保險業                                |          31597|                 36569|      1.157357|              4972|
| 7   | 資訊及通訊傳播業-專業人員                   |          31817|                 36545|      1.148600|              4728|
| 11  | 金融及保險業-技術員及助理專業人員           |          31688|                 35830|      1.130712|              4142|
| 1   | 專業\_科學及技術服務業                      |          29648|                 35666|      1.202982|              6018|
| 8   | 金融及保險業-事務支援人員                   |          30771|                 35278|      1.146469|              4507|
| 4   | 資訊及通訊傳播業                            |          29198|                 33944|      1.162545|              4746|
| 3   | 專業\_科學及技術服務業-技術員及助理專業人員 |          29016|                 33829|      1.165874|              4813|
| 12  | 資訊及通訊傳播業-技術員及助理專業人員       |          28902|                 32354|      1.119438|              3452|
| 2   | 專業\_科學及技術服務業-事務支援人員         |          27035|                 32234|      1.192306|              5199|
| 10  | 資訊及通訊傳播業-事務支援人員               |          27156|                 30856|      1.136250|              3700|

1.  因對金融及保險業有些興趣，及本身以資訊較為專業，故選取此三種有涉及的產業。<br/>
2.  由於在尚未看過此表時，決定考關於資訊相關方面之研究所，因除了本身對資訊的興趣，還認為資訊相關之產業為現代社會之主流，故認為資訊產業之薪水會較高
3.  但從此表得知，有關資訊領域方面之薪水，無論是大學畢業或研究所畢業之薪水並沒有特別高，<br/>然而，多半「金融及保險業」產業薪資意外的高於資訊相關產業，因此，在起薪方面，與原先之想像有些微不同
4.  故為進一步了解「金融及保險業」職業之大學畢業與研究所畢業之薪水是否有明顯漲幅度，故在進行下列分析

``` r
RateRank<-Intrested[order(Intrested$IncreaseRate,decreasing = T),]
knitr::kable(RateRank)
```

| Job                                         |  CollegeSalary|  GraduateSchoolSalary|  IncreaseRate|  GapWithGraAndCol|
|:--------------------------------------------|--------------:|---------------------:|-------------:|-----------------:|
| 專業\_科學及技術服務業                      |          29648|                 35666|      1.202982|              6018|
| 專業\_科學及技術服務業-事務支援人員         |          27035|                 32234|      1.192306|              5199|
| 專業\_科學及技術服務業-技術員及助理專業人員 |          29016|                 33829|      1.165874|              4813|
| 資訊及通訊傳播業                            |          29198|                 33944|      1.162545|              4746|
| 金融及保險業                                |          31597|                 36569|      1.157357|              4972|
| 專業\_科學及技術服務業-專業人員             |          33384|                 38415|      1.150701|              5031|
| 資訊及通訊傳播業-專業人員                   |          31817|                 36545|      1.148600|              4728|
| 金融及保險業-事務支援人員                   |          30771|                 35278|      1.146469|              4507|
| 金融及保險業-專業人員                       |          33646|                 38542|      1.145515|              4896|
| 資訊及通訊傳播業-事務支援人員               |          27156|                 30856|      1.136250|              3700|
| 金融及保險業-技術員及助理專業人員           |          31688|                 35830|      1.130712|              4142|
| 資訊及通訊傳播業-技術員及助理專業人員       |          28902|                 32354|      1.119438|              3452|

1.  由RateRank表與Intrested表對照可知，儘管「金融及保險業」產業薪資較高，但薪資漲幅度卻不比另兩產業顯著，
2.  故儘管資訊相關之產業畢業薪水並未為高於「金融及保險業」，但由於資訊相關產業，研究所畢業與大學畢業之薪資漲幅度仍有明顯之影響，且自己對資訊業相對較有興趣，故仍然會考取有關資訊類之研究所
